### ISSUE TITLE
Update datasets

### ISSUE THREAD

**Issue by sbashevkin** [sbashevkin/discretewq#14]
Another round of updating datasets

Sarah:
- [x] EMP

Liz:
- [x] USGS_CAWSC

Dave: 
- [x] Baystudy
- [x] USGS_SFBS (https://sfbay.wr.usgs.gov/water-quality-database/) 
- [x] SDO
- [x] YBFMP
- [x] 20mm
- [x] SKT

Sam: 
- [x] STN
- [x] FMWT
- [x] EDSM
- [x] DJFMP
- [x] SLS
- [x] Suisun
- [x] USBR

**Comment by sbashevkin** [comment]
USBR hasn't conducted any regular cruises since their data were originally added to this package.

**Comment by mountaindboz** [comment]
Checking in...

- I'm running into all sorts of duplicated records in the YBFMP fish data set. I'm going to contact the group at DWR to sort things out.
- There is only nutrient data up to 8/31/2021 available for USGS_SFBS. I contacted Erica Nejad to see if they plan to add any additional nutrient data in the near future, and she responded that the Sept-Dec 2021 results should be available in a couple of weeks. I'll wait for a few weeks to update the USGS_SFBS data.

**Comment by mountaindboz** [comment]
@sbashevkin - It looks like Baystudy hasn't made any updates to their dataset since the last time you updated the `discretewq` package. I'm not sure when they plan on releasing the 2021 data, so I guess that we can mark that study as complete in this issue for now??

**Comment by sbashevkin** [comment]
@mountaindboz Yeah I guess so. Did you ask them when they plan to release the 2021 data? If not I can ask.

**Comment by mountaindboz** [comment]
@sbashevkin - I didn't ask them, since I'm unsure who to ask. If you have a working relationship with them, it would be great if you could ask them about this. Thanks!

**Comment by sbashevkin** [comment]
@mountaindboz can we close this now?

**Comment by mountaindboz** [comment]
@sbashevkin - I still have a little extra data from SDO that I can add. I'll try to do that today or tomorrow. After that I think we're good!

**Comment by sbashevkin** [comment]
@mountaindboz good to close this now?

**Comment by mountaindboz** [comment]
@sbashevkin Yes!
